on:
  workflow_dispatch: ~
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  check:
    uses: typhoon-php/.github/.github/workflows/check.yml@main
    secrets: inherit
    with:
      php_versions: '["8.2", "8.3", "8.4", "8.5"]'
      infection: false
